### PR TITLE
upgraded aws-java-sdk from 1.10.27 to 1.11.219

### PR DESCRIPTION
**Pull request by rtisma**

### CODE REVIEW

**Comment by rtisma** [comment]
ok to test

**Comment by rtisma** [comment]
add to whitelist

**Comment by rtisma** [comment]
ok to test

**Comment by andricDu** [comment]
add to whitelist

**Comment by rtisma** [comment]
test this please

**Comment by rtisma** [comment]
test this please

**Comment by rtisma** [comment]
test this please

**Comment by rtisma** [comment]
test this please

**Comment by rtisma** [comment]
ok to test

**Pull request merged**
